export const movieData = [
    {
        id: 1,
        title: "Inception",
        genres: ["Action", "Sci-Fi", "Thriller"],
        description: "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.",
        rating: 8.8,
        poster: "https://www.themoviedb.org/t/p/w1280/ljsZTbVsrQSqZgWeep2B1QiDKuh.jpg",
        year: 2010,
        trailer: "https://www.youtube.com/watch?v=8hP9D6kZseM",
        director: "Christopher Nolan",
        leadActors: ["Leonardo DiCaprio", "Joseph Gordon-Levitt", "Ellen Page"],
        length: 148,
        poster_position: 'center'
    },
    {
        id: 2,
        title: "The Matrix",
        genres: ["Action", "Sci-Fi"],
        description: "A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.",
        rating: 8.7,
        poster: "https://m.media-amazon.com/images/M/MV5BN2NmN2VhMTQtMDNiOS00NDlhLTliMjgtODE2ZTY0ODQyNDRhXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
        year: 1999,
        trailer: "https://www.youtube.com/watch?v=vKQi3bBA1y8",
        director: "The Wachowskis",
        leadActors: ["Keanu Reeves", "Laurence Fishburne", "Carrie-Anne Moss"],
        length: 136
    },
    {
        id: 3,
        title: "The Dark Knight",
        genres: ["Action", "Crime", "Drama"],
        description: "When the menace known as The Joker emerges from his mysterious past, he wreaks havoc and chaos on the people of Gotham.",
        rating: 9.0,
        poster: "https://img2.hulu.com/user/v3/artwork/2ce6365a-46e7-43d9-8d77-5b84753a663c?base_image_bucket_name=image_manager&base_image=99f4361c-662b-4693-89d7-7519197f9c40&size=458x687&format=webp",
        year: 2008,
        trailer: "https://www.youtube.com/watch?v=EXeTwQWrcwY",
        director: "Christopher Nolan",
        leadActors: ["Christian Bale", "Heath Ledger", "Aaron Eckhart"],
        length: 152
    },
    {
        id: 4,
        title: "Interstellar",
        genres: ["Adventure", "Drama", "Sci-Fi"],
        description: "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",
        rating: 8.6,
        poster: "https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/p10543523_p_v8_as.jpg",
        year: 2014,
        trailer: "https://www.youtube.com/watch?v=zSWdZVtXT7E",
        director: "Christopher Nolan",
        leadActors: ["Matthew McConaughey", "Anne Hathaway", "Jessica Chastain"],
        length: 169
    },
    {
        id: 5,
        title: "Parasite",
        genres: ["Comedy", "Drama", "Thriller"],
        description: "Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.",
        rating: 8.6,
        poster: "https://play-lh.googleusercontent.com/gh0v4Gv39DwNiI-AKCtUV65G5ExKEot5vtN4EOYPDXR-f49ZsXU2oVfFb4TLi-4Qy0U0",
        year: 2019,
        trailer: "https://www.youtube.com/watch?v=5xH0HfJHsaY",
        director: "Bong Joon Ho",
        leadActors: ["Song Kang-ho", "Lee Sun-kyun", "Cho Yeo-jeong"],
        length: 132
    },
    {
        id: 6,
        title: "Pulp Fiction",
        genres: ["Crime", "Drama"],
        description: "The lives of two mob hitmen, a boxer, a gangster's wife, and a pair of diner bandits intertwine in four tales of violence and redemption.",
        rating: 8.9,
        poster: "https://m.media-amazon.com/images/M/MV5BYTViYTE3ZGQtNDBlMC00ZTAyLTkyODMtZGRiZDg0MjA2YThkXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
        year: 1994,
        trailer: "https://www.youtube.com/watch?v=s7EdQ4FqbhY",
        director: "Quentin Tarantino",
        leadActors: ["John Travolta", "Uma Thurman", "Samuel L. Jackson"],
        length: 154
    },
    {
        id: 7,
        title: "The Shawshank Redemption",
        genres: ["Drama"],
        description: "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.",
        rating: 9.3,
        poster: "https://m.media-amazon.com/images/I/61-vQDr7ecL._AC_UF1000,1000_QL80_.jpg",
        year: 1994,
        trailer: "https://www.youtube.com/watch?v=6hB3S9bIaco",
        director: "Frank Darabont",
        leadActors: ["Tim Robbins", "Morgan Freeman", "Bob Gunton"],
        length: 142
    },
    {
        id: 8,
        title: "The Godfather",
        genres: ["Crime", "Drama"],
        description: "The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.",
        rating: 9.2,
        poster: "https://media.themoviedb.org/t/p/w188_and_h282_bestv2/rPdtLWNsZmAtoZl9PK7S2wE3qiS.jpg",
        year: 1972,
        trailer: "https://www.youtube.com/watch?v=sY1S34973zA",
        director: "Francis Ford Coppola",
        leadActors: ["Marlon Brando", "Al Pacino", "James Caan"],
        length: 175
    },
    {
        id: 9,
        title: "Fight Club",
        genres: ["Drama"],
        description: "An insomniac office worker and a devil-may-care soap maker form an underground fight club that evolves into much more.",
        rating: 8.8,
        poster: "https://media.themoviedb.org/t/p/w188_and_h282_bestv2/bptfVGEQuv6vDTIMVCHjJ9Dz8PX.jpg",
        year: 1999,
        trailer: "https://www.youtube.com/watch?v=SUXWAEX2jlg",
        director: "David Fincher",
        leadActors: ["Brad Pitt", "Edward Norton", "Helena Bonham Carter"],
        length: 139,
        poster_position: 'center'
    },
    {
        id: 10,
        title: "Forrest Gump",
        genres: ["Drama", "Romance"],
        description: "The presidencies of Kennedy and Johnson, the Vietnam War, the Watergate scandal and other historical events unfold from the perspective of an Alabama man with an IQ of 75.",
        rating: 8.8,
        poster: "https://media.themoviedb.org/t/p/w188_and_h282_bestv2/clolk7rB5lAjs41SD0Vt6IXYLMm.jpg",
        year: 1994,
        trailer: "https://www.youtube.com/watch?v=bLvqoHBptjg",
        director: "Robert Zemeckis",
        leadActors: ["Tom Hanks", "Robin Wright", "Gary Sinise"],
        length: 142,
        poster_position: 'center'
    },
    {
        id: 11,
        title: "The Fellowship of the Ring", // i shortened it
        genres: ["Adventure", "Drama", "Fantasy"],
        description: "A meek Hobbit and eight companions set out on a journey to destroy the powerful One Ring and save Middle-earth.",
        rating: 8.8,
        poster: "https://media.themoviedb.org/t/p/w188_and_h282_bestv2/6oom5QYQ2yQTMJIbnvbkBL9cHo6.jpg",
        year: 2001,
        trailer: "https://www.youtube.com/watch?v=V75dMMIW2B4",
        director: "Peter Jackson",
        leadActors: ["Elijah Wood", "Ian McKellen", "Orlando Bloom"],
        length: 178
    },
    {
        id: 12,
        title: "The Lion King",
        genres: ["Animation", "Adventure", "Drama"],
        description: "Lion prince Simba and his father are targeted by his bitter uncle, who wants to ascend the throne himself.",
        rating: 8.5,
        poster: "https://media.themoviedb.org/t/p/w188_and_h282_bestv2/sKCr78MXSLixwmZ8DyJLrpMsd15.jpg",
        year: 1994,
        trailer: "https://www.youtube.com/watch?v=4sj1MT05lAA",
        director: "Roger Allers, Rob Minkoff",
        leadActors: ["Matthew Broderick", "Jeremy Irons", "James Earl Jones"],
        length: 88
    },
    {
        id: 13,
        title: "Gladiator",
        genres: ["Action", "Adventure", "Drama"],
        description: "A former Roman General sets out to exact vengeance against the corrupt emperor who murdered his family and sent him into slavery.",
        rating: 8.5,
        poster: "https://media.themoviedb.org/t/p/w188_and_h282_bestv2/ty8TGRuvJLPUmAR1H1nRIsgwvim.jpg",
        year: 2000,
        trailer: "https://www.youtube.com/watch?v=owK1qxDselE",
        director: "Ridley Scott",
        leadActors: ["Russell Crowe", "Joaquin Phoenix", "Connie Nielsen"],
        length: 155
    },
    {
        id: 14,
        title: "Avatar",
        genres: ["Action", "Adventure", "Fantasy"],
        description: "A paraplegic Marine dispatched to the moon Pandora on a unique mission becomes torn between following orders and protecting the world he feels is his home.",
        rating: 7.8,
        poster: "https://media.themoviedb.org/t/p/w188_and_h282_bestv2/6EiRUJpuoeQPghrs3YNktfnqOVh.jpg",
        year: 2009,
        trailer: "https://www.youtube.com/watch?v=5PSNL1qE6VY",
        director: "James Cameron",
        leadActors: ["Sam Worthington", "Zoe Saldana", "Sigourney Weaver"],
        length: 162
    },
    {
        id: 15,
        title: "Titanic",
        genres: ["Drama", "Romance"],
        description: "A seventeen-year-old aristocrat falls in love with a kind but poor artist aboard the luxurious, ill-fated R.M.S. Titanic.",
        rating: 7.9,
        poster: "https://media.themoviedb.org/t/p/w188_and_h282_bestv2/9xjZS2rlVxm8SFx8kPC3aIGCOYQ.jpg",
        year: 1997,
        trailer: "https://www.youtube.com/watch?v=kVrqfYjkTdQ",
        director: "James Cameron",
        leadActors: ["Leonardo DiCaprio", "Kate Winslet", "Billy Zane"],
        length: 195
    },
    {
        id: 16,
        title: "The Avengers",
        genres: ["Action", "Adventure", "Sci-Fi"],
        description: "Earth's mightiest heroes must come together and learn to fight as a team if they are going to stop the mischievous Loki and his alien army from enslaving humanity.",
        rating: 8.0,
        poster: "https://media.themoviedb.org/t/p/w188_and_h282_bestv2/RYMX2wcKCBAr24UyPD7xwmjaTn.jpg",
        year: 2012,
        trailer: "https://www.youtube.com/watch?v=eOrNdBpGMv8",
        director: "Joss Whedon",
        leadActors: ["Robert Downey Jr.", "Chris Evans", "Scarlett Johansson"],
        length: 143,
        poster_position: 'top'
    },
    {
        id: 17,
        title: "Jurassic Park",
        genres: ["Adventure", "Sci-Fi", "Thriller"],
        description: "A pragmatic paleontologist visiting an almost complete theme park is tasked with protecting a couple of kids after a power failure causes the park's cloned dinosaurs to run loose.",
        rating: 8.1,
        poster: "https://media.themoviedb.org/t/p/w94_and_h141_bestv2/oU7Oq2kFAAlGqbU4VoAE36g4hoI.jpg",
        year: 1993,
        trailer: "https://www.youtube.com/watch?v=lc0UehYemQA",
        director: "Steven Spielberg",
        leadActors: ["Sam Neill", "Laura Dern", "Jeff Goldblum"],
        length: 127,
        poster_position: 'center'
        
    },
    //Harry Had to go that title was too long LOL
    {
        id: 18,
        title: "Back to the Future",
        genres: ["Adventure", "Comedy", "Sci-Fi"],
        description: "Marty McFly, a 17-year-old high school student, is accidentally sent thirty years into the past in a time-traveling DeLorean invented by his close friend, eccentric scientist Doc Brown.",
        rating: 8.5,
        poster: "https://media.themoviedb.org/t/p/w188_and_h282_bestv2/7lyBcpYB0Qt8gYhXYaEZUNlNQAv.jpg",
        year: 1985,
        trailer: "https://www.youtube.com/watch?v=qvsgGtivCgs",
        director: "Robert Zemeckis",
        leadActors: ["Michael J. Fox", "Christopher Lloyd", "Lea Thompson"],
        length: 116,
        poster_position: 'center'
    },
    {
        id: 19,
        title: "The Green Mile",
        genres: ["Crime", "Drama", "Fantasy"],
        description: "The lives of guards on Death Row are affected by one of their charges: a black man accused of child murder and rape, yet who has a mysterious gift.",
        rating: 8.6,
        poster: "https://media.themoviedb.org/t/p/w188_and_h282_bestv2/sOHqdY1RnSn6kcfAHKu28jvTebE.jpg",
        year: 1999,
        trailer: "https://www.youtube.com/watch?v=Ki4haFrqSrw",
        director: "Frank Darabont",
        leadActors: ["Tom Hanks", "Michael Clarke Duncan", "David Morse"],
        length: 189
    }
];
