export const showData = [
    {
        "id": 1,
        "title": "Stranger Things",
        "genres": ["Drama", "Fantasy", "Horror"],
        "description": "When a young boy disappears, his mother, a police chief, and his friends confront terrifying supernatural forces in order to get him back.",
        "rating": 8.7,
        "poster": "https://media.themoviedb.org/t/p/w188_and_h282_bestv2/uOOtwVbSr4QDjAGIifLDwpb2Pdl.jpg",
        "studio": "21 Laps Entertainment",
        "episodes": 34,
        "year_started": 2016,
        "year_final": "Ongoing",
        "seasons": 4,
        "lead_actors": ["Winona Ryder", "David Harbour", "Finn Wolfhard"],
        "trailer": "https://www.youtube.com/watch?v=b9EkMc79ZSU"
    },
    {
        "id": 2,
        "title": "Breaking Bad",
        "genres": ["Crime", "Drama", "Thriller"],
        "description": "A high school chemistry teacher turned methamphetamine manufacturer navigates the drug trade with his former student.",
        "rating": 9.5,
        "poster": "https://media.themoviedb.org/t/p/w188_and_h282_bestv2/ztkUQFLlC19CCMYHW9o1zWhJRNq.jpg",
        "studio": "Sony Pictures Television",
        "episodes": 62,
        "year_started": 2008,
        "year_final": 2013,
        "seasons": 5,
        "lead_actors": ["Bryan Cranston", "Aaron Paul", "Anna Gunn"],
        "trailer": "https://www.youtube.com/watch?v=HhesaQXLuRY"
    },
    {
        "id": 3,
        "title": "The Office",
        "genres": ["Comedy"],
        "description": "A mockumentary on a group of typical office workers, where the workday consists of ego clashes, inappropriate behavior, and tedium.",
        "rating": 8.9,
        "poster": "https://media.themoviedb.org/t/p/w188_and_h282_bestv2/7DJKHzAi83BmQrWLrYYOqcoKfhR.jpg",
        "studio": "NBC Universal Television",
        "episodes": 201,
        "year_started": 2005,
        "year_final": 2013,
        "seasons": 9,
        "lead_actors": ["Steve Carell", "Rainn Wilson", "John Krasinski"],
        "trailer": "https://www.youtube.com/watch?v=fyj8j4zBl9w"
    },
    {
        "id": 4,
        "title": "Game of Thrones",
        "genres": ["Action", "Adventure", "Drama"],
        "description": "Nine noble families wage war against each other in order to gain control over the mythical land of Westeros.",
        "rating": 9.3,
        "poster": "https://media.themoviedb.org/t/p/w188_and_h282_bestv2/1XS1oqL89opfnbLl8WnZY1O1uJx.jpg",
        "studio": "HBO",
        "episodes": 73,
        "year_started": 2011,
        "year_final": 2019,
        "seasons": 8,
        "lead_actors": ["Emilia Clarke", "Kit Harington", "Lena Headey"],
        "trailer": "https://www.youtube.com/watch?v=KPLWWIOCOOQ"
    },
    {
        "id": 5,
        "title": "The Mandalorian",
        "genres": ["Action", "Adventure", "Fantasy"],
        "description": "The travels of a lone bounty hunter in the outer reaches of the galaxy, far from the authority of the New Republic.",
        "rating": 8.8,
        "poster": "https://media.themoviedb.org/t/p/w188_and_h282_bestv2/eU1i6eHXlzMOlEq0ku1Rzq7Y4wA.jpg",
        "studio": "Lucasfilm",
        "episodes": 24,
        "year_started": 2019,
        "year_final": "Ongoing",
        "seasons": 3,
        "lead_actors": ["Pedro Pascal", "Gina Carano", "Carl Weathers"],
        "trailer": "https://www.youtube.com/watch?v=aOC8E8z_ifw"
    },
    {
        "id": 6,
        "title": "Friends",
        "genres": ["Comedy", "Romance"],
        "description": "Follows the personal and professional lives of six twenty to thirty-something-year-old friends living in Manhattan.",
        "rating": 8.9,
        "poster": "https://media.themoviedb.org/t/p/w188_and_h282_bestv2/2koX1xLkpTQM4IZebYvKysFW1Nh.jpg",
        "studio": "Warner Bros. Television",
        "episodes": 236,
        "year_started": 1994,
        "year_final": 2004,
        "seasons": 10,
        "lead_actors": ["Jennifer Aniston", "Courteney Cox", "Lisa Kudrow"],
        "trailer": "https://www.youtube.com/watch?v=hDNNmeeJs1Q"
    },
    {
        "id": 7,
        "title": "Sherlock",
        "genres": ["Crime", "Drama", "Mystery"],
        "description": "A modern update finds the famous sleuth and his doctor partner solving crime in 21st century London.",
        "rating": 9.1,
        "poster": "https://media.themoviedb.org/t/p/w188_and_h282_bestv2/7WTsnHkbA0FaG6R9twfFde0I9hl.jpg",
        "studio": "Hartswood Films",
        "episodes": 13,
        "year_started": 2010,
        "year_final": 2017,
        "seasons": 4,
        "lead_actors": ["Benedict Cumberbatch", "Martin Freeman", "Una Stubbs"],
        "trailer": "https://www.youtube.com/watch?v=xK7S9mrFWL4"
    },
    {
        "id": 8,
        "title": "The Crown",
        "genres": ["Drama", "History"],
        "description": "Follows the political rivalries and romance of Queen Elizabeth II's reign and the events that shaped the second half of the 20th century.",
        "rating": 8.6,
        "poster": "https://media.themoviedb.org/t/p/w188_and_h282_bestv2/1M876KPjulVwppEpldhdc8V4o68.jpg",
        "studio": "Left Bank Pictures",
        "episodes": 60,
        "year_started": 2016,
        "year_final": "Ongoing",
        "seasons": 5,
        "lead_actors": ["Claire Foy", "Olivia Colman", "Imelda Staunton"],
        "trailer": "https://www.youtube.com/watch?v=JWtnJjn6ng0"
    },
    {
        "id": 9,
        "title": "The Witcher",
        "genres": ["Action", "Adventure", "Drama"],
        "description": "Geralt of Rivia, a mutated monster-hunter for hire, journeys toward his destiny in a turbulent world where people often prove more wicked than beasts.",
        "rating": 8.2,
        "poster": "https://media.themoviedb.org/t/p/w188_and_h282_bestv2/cZ0d3rtvXPVvuiX22sP79K3Hmjz.jpg",
        "studio": "Platige Image",
        "episodes": 24,
        "year_started": 2019,
        "year_final": "Ongoing",
        "seasons": 3,
        "lead_actors": ["Henry Cavill", "Anya Chalotra", "Freya Allan"],
        "trailer": "https://www.youtube.com/watch?v=ndl1W4ltcmg"
    },
    {
        "id": 10,
        "title": "The Simpsons",
        "genres": ["Animation", "Comedy"],
        "description": "The satiric adventures of a working-class family in the misfit city of Springfield.",
        "rating": 8.7,
        "poster": "https://media.themoviedb.org/t/p/w188_and_h282_bestv2/qcr9bBY6MVeLzriKCmJOv1562uY.jpg",
        "studio": "Gracie Films",
        "episodes": 750,
        "year_started": 1989,
        "year_final": "Ongoing",
        "seasons": 35,
        "lead_actors": ["Dan Castellaneta", "Julie Kavner", "Nancy Cartwright"],
        "trailer": "https://www.youtube.com/watch?v=NVcMifZb9mM"
    },
    {
        "id": 11,
        "title": "House of Cards",
        "genres": ["Drama"],
        "description": "A congressman works with his equally conniving wife to exact revenge on the people who betrayed him.",
        "rating": 8.7,
        "poster": "https://media.themoviedb.org/t/p/w188_and_h282_bestv2/hKWxWjFwnMvkWQawbhvC0Y7ygQ8.jpg",
        "studio": "Media Rights Capital",
        "episodes": 73,
        "year_started": 2013,
        "year_final": 2018,
        "seasons": 6,
        "lead_actors": ["Kevin Spacey", "Robin Wright", "Michael Kelly"],
        "trailer": "https://www.youtube.com/watch?v=ULwUzF1q5w4"
    },
    {
        "id": 12,
        "title": "Ozark",
        "genres": ["Crime", "Drama", "Thriller"],
        "description": "A financial advisor drags his family from Chicago to the Missouri Ozarks, where he must launder money to appease a drug boss.",
        "rating": 8.4,
        "poster": "https://media.themoviedb.org/t/p/w188_and_h282_bestv2/pCGyPVrI9Fzw6rE1Pvi4BIXF6ET.jpg",
        "studio": "Media Rights Capital",
        "episodes": 44,
        "year_started": 2017,
        "year_final": 2022,
        "seasons": 4,
        "lead_actors": ["Jason Bateman", "Laura Linney", "Julia Garner"],
        "trailer": "https://www.youtube.com/watch?v=5hAXVqrljbs"
    },
    {
        "id": 13,
        "title": "The Boys",
        "genres": ["Action", "Comedy", "Crime"],
        "description": "A group of vigilantes set out to take down corrupt superheroes who abuse their superpowers.",
        "rating": 8.7,
        "poster": "https://media.themoviedb.org/t/p/w188_and_h282_bestv2/stTEycfG9928HYGEISBFaG1ngjM.jpg",
        "studio": "Sony Pictures Television",
        "episodes": 24,
        "year_started": 2019,
        "year_final": "Ongoing",
        "seasons": 3,
        "lead_actors": ["Karl Urban", "Jack Quaid", "Antony Starr"],
        "trailer": "https://www.youtube.com/watch?v=Mxbl9rZ5Ftg"
    },
    {
        "id": 14,
        "title": "Westworld",
        "genres": ["Drama", "Mystery", "Sci-Fi"],
        "description": "Set at the intersection of the near future and the reimagined past, explore a world in which every human appetite can be indulged without consequence.",
        "rating": 8.6,
        "poster": "https://media.themoviedb.org/t/p/w188_and_h282_bestv2/y55oBgf6bVMI7sFNXwJDrSIxPQt.jpg",
        "studio": "Warner Bros. Television",
        "episodes": 36,
        "year_started": 2016,
        "year_final": 2022,
        "seasons": 4,
        "lead_actors": ["Evan Rachel Wood", "Thandiwe Newton", "Jeffrey Wright"],
        "trailer": "https://www.youtube.com/watch?v=deSUQ7mZfWk"
    },
    {
        "id": 15,
        "title": "Peaky Blinders",
        "genres": ["Crime", "Drama"],
        "description": "A gangster family epic set in 1919 Birmingham, England, and centered on a gang who sew razor blades in the peaks of their caps.",
        "rating": 8.8,
        "poster": "https://media.themoviedb.org/t/p/w188_and_h282_bestv2/vUUqzWa2LnHIVqkaKVlVGkVcZIW.jpg",
        "studio": "BBC Studios",
        "episodes": 36,
        "year_started": 2013,
        "year_final": 2022,
        "seasons": 6,
        "lead_actors": ["Cillian Murphy", "Paul Anderson", "Helen McCrory"],
        "trailer": "https://www.youtube.com/watch?v=oVzVdvGIC7U"
    },
    {
        "id": 16,
        "title": "The Flash",
        "genres": ["Action", "Adventure", "Drama"],
        "description": "After being struck by lightning, Barry Allen wakes up from his coma to discover he's been given the power of super speed, becoming the Flash.",
        "rating": 7.6,
        "poster": "https://media.themoviedb.org/t/p/w188_and_h282_bestv2/lJA2RCMfsWoskqlQhXPSLFQGXEJ.jpg",
        "studio": "Warner Bros. Television",
        "episodes": 184,
        "year_started": 2014,
        "year_final": 2023,
        "seasons": 9,
        "lead_actors": ["Grant Gustin", "Candice Patton", "Danielle Panabaker"],
        "trailer": "https://www.youtube.com/watch?v=Yj0l7iGKh8g"
    },
    {
        "id": 17,
        "title": "Vikings",
        "genres": ["Action", "Adventure", "Drama"],
        "description": "Follow the exploits of Ragnar Lothbrok, a legendary Viking chieftain and his crew, as they take on the world.",
        "rating": 8.5,
        "poster": "https://media.themoviedb.org/t/p/w188_and_h282_bestv2/bQLrHIRNEkE3PdIWQrZHynQZazu.jpg",
        "studio": "MGM Television",
        "episodes": 89,
        "year_started": 2013,
        "year_final": 2020,
        "seasons": 6,
        "lead_actors": ["Travis Fimmel", "Katheryn Winnick", "Clive Standen"],
        "trailer": "https://www.youtube.com/watch?v=9GgxinPwAGc"
    },
    {
        "id": 18,
        "title": "Lucifer",
        "genres": ["Crime", "Drama", "Fantasy"],
        "description": "Lucifer Morningstar has decided he's had enough of being the dutiful servant in Hell and decides to spend some time on Earth to better understand humanity.",
        "rating": 8.1,
        "poster": "https://media.themoviedb.org/t/p/w188_and_h282_bestv2/ekZobS8isE6mA53RAiGDG93hBxL.jpg",
        "studio": "Warner Bros. Television",
        "episodes": 93,
        "year_started": 2016,
        "year_final": 2021,
        "seasons": 6,
        "lead_actors": ["Tom Ellis", "Lauren German", "Kevin Alejandro"],
        "trailer": "https://www.youtube.com/watch?v=X4bF_quwNtw"
    },
    {
        "id": 19,
        "title": "Mindhunter",
        "genres": ["Crime", "Drama", "Thriller"],
        "description": "Set in the late 1970s, two FBI agents expand criminal science by delving into the psychology of murder and getting uneasily close to all-too-real monsters.",
        "rating": 8.6,
        "poster": "https://media.themoviedb.org/t/p/w188_and_h282_bestv2/fbKE87mojpIETWepSbD5Qt741fp.jpg",
        "studio": "Netflix",
        "episodes": 19,
        "year_started": 2017,
        "year_final": 2019,
        "seasons": 2,
        "lead_actors": ["Jonathan Groff", "Holt McCallany", "Anna Torv"],
        "trailer": "https://www.youtube.com/watch?v=LR3G1lWbnUU"
    },
    {
        "id": 20,
        "title": "The Umbrella Academy",
        "genres": ["Action", "Adventure", "Comedy"],
        "description": "A dysfunctional family of superheroes comes together to solve the mystery of their father's death, the threat of the apocalypse, and more.",
        "rating": 8.0,
        "poster": "https://media.themoviedb.org/t/p/w188_and_h282_bestv2/uYHdIs5O8tiU5p6MvUPd2jElOH6.jpg",
        "studio": "Netflix",
        "episodes": 30,
        "year_started": 2019,
        "year_final": "Ongoing",
        "seasons": 3,
        "lead_actors": ["Elliot Page", "Tom Hopper", "David Castañeda"],
        "trailer": "https://www.youtube.com/watch?v=0DAmWHxeoKw"
    }
];
